#pragma once
#include <windows.h>

namespace lightsout {
	enum ForegroundColors {
		FG_Black = 0x0000,
		FG_Red = FOREGROUND_RED,
		FG_Magenta = FOREGROUND_RED | FOREGROUND_BLUE,
		FG_Green = FOREGROUND_GREEN,
		FG_Brown = FOREGROUND_RED | FOREGROUND_GREEN,
		FG_Yellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
		FG_Blue = FOREGROUND_BLUE,
		FG_Cyan = FOREGROUND_GREEN | FOREGROUND_BLUE,
		FG_Gray = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
		FG_White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
	};

	enum BackgroundColors {
		BG_Black = 0x0000,
		BG_Red = BACKGROUND_RED,
		BG_Magenta = BACKGROUND_RED | BACKGROUND_BLUE,
		BG_Green = BACKGROUND_GREEN,
		BG_Brown = BACKGROUND_RED | BACKGROUND_GREEN,
		BG_Yellow = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
		BG_Blue = BACKGROUND_BLUE,
		BG_Cyan = BACKGROUND_GREEN | BACKGROUND_BLUE,
		BG_Gray = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
		BG_White = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
	};
}